defaults:
  - _self_
  - train: default
  - data: default
  - model: default
  - loss: default
  - optimization: default
  
hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

ckpt_directory: checkpoints
name: "debug"
